# Generated by Django 5.2.15 on 2026-06-10 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='crt_dt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='mdfcn_dt')),
                ('sn', models.IntegerField(db_column='user_sn', primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_column='user_id', max_length=20, unique=True)),
                ('password', models.CharField(db_column='user_pswd', max_length=256)),
                ('name', models.CharField(db_column='user_nm', max_length=100)),
                ('department', models.CharField(blank=True, db_column='dept_nm', max_length=100, null=True)),
                ('position', models.CharField(blank=True, db_column='jbgd_nm', max_length=100, null=True)),
                ('sys_mngr_yn', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_column='sys_mngr_yn', default='N', max_length=1)),
                ('tmpr_pswd_yn', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_column='tmpr_pswd_yn', default='N', max_length=1)),
                ('use_yn', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_column='use_yn', default='Y', max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_column='creatr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='mdfr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'tbl_user',
            },
        ),
    ]
