# Generated by Django 5.2.15 on 2026-06-10 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='crt_dt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='mdfcn_dt')),
                ('is_deleted', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_column='del_yn', default='N', max_length=1)),
                ('sn', models.IntegerField(db_column='prj_sn', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='prj_nm', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, db_column='creatr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='mdfr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'tbl_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectNet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='crt_dt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='mdfcn_dt')),
                ('sn', models.IntegerField(db_column='prj_net_sn', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='prj_net_nm', max_length=100)),
                ('purpose', models.CharField(blank=True, db_column='prj_net_prps', max_length=1000, null=True)),
                ('middleware_stack', models.CharField(blank=True, db_column='mid_stack', max_length=1000, null=True)),
                ('firewall_settings', models.CharField(blank=True, db_column='fwl_settings', max_length=1000, null=True)),
                ('auth_method', models.CharField(blank=True, db_column='auth_method', max_length=1000, null=True)),
                ('expected_concurrent_users', models.IntegerField(blank=True, db_column='expected_smtn', null=True)),
                ('cloud_yn', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], db_column='cloud_yn', max_length=1, null=True)),
                ('hardware_spec', models.CharField(blank=True, db_column='hard_spec', max_length=1000, null=True)),
                ('remarks', models.CharField(blank=True, db_column='rmrk', max_length=1000, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='creatr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='prj_sn', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='nets', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, db_column='mdfr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project network',
                'verbose_name_plural': 'project networks',
                'db_table': 'tbl_project_net',
            },
        ),
        migrations.CreateModel(
            name='ProjectUserRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='crt_dt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='mdfcn_dt')),
                ('sn', models.IntegerField(db_column='prj_user_role_sn', primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='creatr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='prj_sn', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='projects.project')),
                ('role', models.ForeignKey(db_column='role_cd', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='project_roles', to='common.code')),
                ('updated_by', models.ForeignKey(blank=True, db_column='mdfr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_sn', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='project_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project user role',
                'verbose_name_plural': 'project user roles',
                'db_table': 'tbl_project_user_role',
            },
        ),
    ]
