# Generated by Django 5.2.15 on 2026-06-10 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='crt_dt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='mdfcn_dt')),
                ('code', models.CharField(db_column='code', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='code_nm', max_length=100)),
                ('remarks', models.CharField(blank=True, db_column='rmrk_cn', max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='creatr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='mdfr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'code',
                'verbose_name_plural': 'codes',
                'db_table': 'tbl_code',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='crt_dt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='mdfcn_dt')),
                ('sn', models.IntegerField(db_column='file_sn', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='file_nm', max_length=100)),
                ('path', models.CharField(db_column='file_path', max_length=300)),
                ('content', models.BinaryField(db_column='file_cn')),
                ('size', models.IntegerField(db_column='file_size')),
                ('extension', models.CharField(db_column='file_ext', max_length=4)),
                ('created_by', models.ForeignKey(blank=True, db_column='creatr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('file_type', models.ForeignKey(db_column='file_cd', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='project_files', to='common.code')),
            ],
            options={
                'verbose_name': 'project file',
                'verbose_name_plural': 'project files',
                'db_table': 'tbl_file',
            },
        ),
    ]
