# Generated by Django 5.2.15 on 2026-06-10 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(db_column='prj_sn', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='mdfr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
