@host = http://localhost:8000
@projectSn = 1
@rfpFileSn = 3
@meetingFileSn = 2

### Health check
GET {{host}}/health

### Generate SRS from RFP
POST {{host}}/generate
Content-Type: application/json

{
  "project_sn": {{projectSn}},
  "docs_cd": "ERD",
  "udt_yn": "N",
  "file_list": [],
  "image_list": [],
  "etc": {
    "debug": true
  }
}
