@host = http://localhost:8000
@projectSn = 1
@rfpFileSn = 3
@meetingFileSn = 2


### docs_cd
# 사용자 요구사항 정의서: "DOC_SRS"
# 사용자 인터페이스 설계서: "DOC_ITF"
# 아키텍처 설계서: "DOC_ARCH"
# 엔티티 관계 모형: "DOC_ERD"
# 데이터베이스 설계서: "DOC_DB"
# 통합 시험 시나리오: "DOC_TS"



### Health check
GET {{host}}/health

### Generate SRS from RFP
POST {{host}}/generate
Content-Type: application/json

{
  "project_sn": {{projectSn}},
  "docs_cd": "SRS",
  "udt_yn": "N",
  "file_list": [3, 2],
  "image_list": [],
  "etc": {
    "debug": true
  }
}

### Generate INTERFACE from RFP
POST {{host}}/generate
Content-Type: application/json

{
  "project_sn": {{projectSn}},
  "docs_cd": "INTERFACE",
  "udt_yn": "N",
  "file_list": [],
  "image_list": [24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
  "etc": {
    "debug": true
  }
}

### Generate ERD from RFP
POST {{host}}/generate
Content-Type: application/json

{
  "project_sn": {{projectSn}},
  "docs_cd": "ERD",
  "udt_yn": "N",
  "file_list": [2],
  "image_list": [],
  "etc": {
    "debug": true
  }
}



### Generate ARCH from RFP
POST {{host}}/generate
Content-Type: application/json

{
  "project_sn": {{projectSn}},
  "docs_cd": "ARCH",
  "udt_yn": "N",
  "file_list": [60],
  "image_list": [],
  "etc": {
    "debug": true
  }
}

# [60]     → 요구사항 기준으로 ARCH 생성/수정
# [2]  → 기존 ARCH + 회의록 변경사항 반영, 추천

### Generate ARCH from RFP
POST {{host}}/generate
Content-Type: application/json

{
  "project_sn": {{projectSn}},
  "docs_cd": "ARCH",
  "udt_yn": "Y",
  "file_list": [2],
  "image_list": [],
  "etc": {
    "debug": true
  }
}
