# Generated by Django 5.2.15 on 2026-06-10 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='crt_dt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='mdfcn_dt')),
                ('sn', models.IntegerField(db_column='docs_sn', primary_key=True, serialize=False)),
                ('version', models.CharField(db_column='docs_ver', max_length=20)),
                ('modification_content', models.CharField(db_column='mdfcn_cn', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, db_column='creatr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(db_column='docs_cd', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='common.code')),
                ('project', models.ForeignKey(db_column='prj_sn', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, db_column='mdfr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_sn', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'db_table': 'tbl_docs',
            },
        ),
        migrations.CreateModel(
            name='DocumentDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='crt_dt')),
                ('is_deleted', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], db_column='del_yn', default='N', max_length=1)),
                ('sn', models.IntegerField(db_column='docs_dtl_sn', primary_key=True, serialize=False)),
                ('content', models.BinaryField(blank=True, db_column='docs_dtl_cn', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='creatr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(db_column='docs_sn', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='details', to='docs.document')),
            ],
            options={
                'verbose_name': 'document detail',
                'verbose_name_plural': 'document details',
                'db_table': 'tbl_docs_detail',
            },
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='crt_dt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='mdfcn_dt')),
                ('sn', models.IntegerField(db_column='docsaprv_sn', primary_key=True, serialize=False)),
                ('request_content', models.CharField(db_column='dmnd_cn', max_length=100)),
                ('rejection_reason', models.CharField(db_column='rjct_rsn', max_length=100)),
                ('approval_status', models.ForeignKey(db_column='aprv_stts_cd', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='document_approvals', to='common.code')),
                ('created_by', models.ForeignKey(blank=True, db_column='creatr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='mdfr_sn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('detail', models.ForeignKey(db_column='docs_dtl_sn', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='docs.documentdetail')),
            ],
            options={
                'verbose_name': 'document approval',
                'verbose_name_plural': 'document approvals',
                'db_table': 'tbl_docs_approve',
            },
        ),
    ]
